### PR TITLE
Add nodejs rtsp-ffmpeg

### PR DESCRIPTION
**Pull request by pacozaa**
Add nodejs rtsp-ffmpeg which focus on video streaming. You instead of ffserver in case you use windows os or prefer nodejs

### CODE REVIEW

**Comment by TimothyGu** [comment]
It is not part of FFmpeg, which that file is supposed to describe.

And, for any other users seeking an FFmpeg binding in Node.js, **there is no officially endorsed Node.js module for FFmpeg.**

**Comment by TimothyGu** [comment]
And, in case you want to submit another patch, see #153.

**Comment by KamranMackey** [comment]
@TimothyGu If you don't want people to submit PRs here, add a CONTRIBUTING.md file.

**Comment by pacozaa** [comment]
Oh sorry,sir. It's ok.

**Pull request closed without merging**
