### PR TITLE
Image exr transfer characteristics

### PR DESCRIPTION
**Pull request by KevinJW**
Not sure if this will need an API bump, it does add an extra function so I assume so, but have not included it in the patch set.

It facilitates more non-linear encodings to be applied to OpenEXR inputs including SMPTE HDR options, etc.

I'd like to extend it to also include other non-standardised transforms in the future to allow for ARRI's LogC and similar for Red and Sony camera options, but this set of patches I believe to be complete for all the transfer characteristics referenced by ITU-T H.265 04/2015.

Kevin

### CODE REVIEW

**Comment by richardpl** [comment]
The last one need to be squashed with rest of patches.

**Comment by KevinJW** [comment]
Could I just check you mean squash the reserved names one (bd7de52) into the one that creates the function in the first place (01f37e4), and not to squash all of them into a single one?

**Comment by richardpl** [comment]
yes i mean reserved func should not be in history.

**Comment by michaelni** [comment]
patches applied
thanks

**Pull request closed without merging**
