### PR TITLE
Used to add NEON optimization for Aarch64 HEVC decoder

### PR DESCRIPTION
**Pull request by zjh8890**
This commit finished IDCT NEON optimization for aarch64 HEVC decoder, and many h265 stream test 
vedio have been tested by the optimed HEVC, the point have be increased 30% according to the org.

### CODE REVIEW

**Comment by michaelni** [comment]
This is missing the "hevcdsp_aarch64.h" file
libavcodec/aarch64/hevcdsp_init_neon.c:25:29: fatal error: hevcdsp_aarch64.h: No such file or directory

**Comment by zjh8890** [comment]
Who can commit the request for HEVC arm64 optimization?

**Comment by michaelni** [comment]
it still doesnt build
i suggest you test your patches on a clean checkout before submitting

make
AR	libavcodec/libavcodec.a
/usr/aarch64-linux-gnu/bin/ar: libavcodec/aarch64/hevcdsp_init_aarch64.o: No such file or directory
/home/michael/ffmpeg/ffmpeg/library.mak:40: recipe for target 'libavcodec/libavcodec.a' failed
make: *** [libavcodec/libavcodec.a] Error 1

**Comment by zjh8890** [comment]
I have checkout while submitting my code, and  added qpel function aarch64 neon optimization for HEVC decoder. I am sorry for not familiar with operation of github. But I hope the software decoder of HEVC have be helpful to others.

**Comment by TimothyGu** [comment]
We don't use GitHub. I see that you have already submitted the patches through email, and I'll close this pull request.

It is mandatory to read our [development policies](https://www.ffmpeg.org/developer.html#Development-Policy). In your case, you have to make at least the following changes:

1. make one commit represent one change (don't have a bunch of "add ... file" commits that don't work when committed alone)
2. fix your commit messages, which are lacking at best. Say what it does "hevc: Optimize function xxxx_xxx for AArch64" not what it adds "Add xxxfile.S"

If you have any questions, please ask on the mailing list.

**Pull request closed without merging**
