### PR TITLE
Update neon.s for transpose_4x4H

### PR DESCRIPTION
**Pull request by zjh8890**
The transpose_4x4H is wrong which cost me much time to find this bug. The orders of r2 and r3 are wrong,
this bug waste me much time while I make aarch64 arm instruction which used the function.

### CODE REVIEW

**Comment by TimothyGu** [comment]
See #153.

**Comment by richardpl** [comment]
Stop closing pull requests, please!

**Comment by michaelni** [comment]
patch applied
thanks

**Comment by gaming-hacker** [comment]
good catch, thanks, i applied it.

**Pull request closed without merging**
