### PR TITLE
Request for merging changes

### PR DESCRIPTION
**Pull request by Sami32**
Sorry, i'm really not familiar with that, so i hope that this time i did it correctly ?

From _contributing.md_ :
> Committing changes to a git clone, for example on github.com or gitorious.org. And asking us to merge these changes.

https://github.com/Matroska-Org/matroska-specification/blob/a2de2b67338fc6f5f64d58e0a65df88850eaca76/codec_specs.md#subtitle-codec-mappings

Add USF, WEBVTT, BMP and KATE to the subtitles list.

### CODE REVIEW

**Comment by BtbN** [comment]
Patches should be submitted to the [ffmpeg-devel mailing list](https://ffmpeg.org/mailman/listinfo/ffmpeg-devel) using `git format-patch` or `git send-email`. Github pull requests should be avoided because they are not part of our review process and **will be ignored**.

See [https://ffmpeg.org/developer.html#Contributing](https://ffmpeg.org/developer.html#Contributing) for more information.

**Comment by Sami32** [comment]
@BtbN So perhaps you should respect what you write or modify it...It's not fair at all, IMO.
> 1.2 Contributing
> 
> There are 3 ways by which code gets into FFmpeg.
> 
>- Submitting patches to the main developer mailing list. See Submitting patches for details.
>- Directly committing changes to the main tree.
>- **Committing changes to a git clone, for example on github.com or gitorious.org. And asking us to merge these changes.** 
> 
> Whichever way, changes should be reviewed by the maintainer of the code before they are committed. And they should follow the Coding Rules. The developer making the commit and the author are responsible for their changes and should try to fix issues their commit causes.

**Comment by BtbN** [comment]
Even in that case, you should send it to the mailing lists mentioned in the very first sentence of the contributing.md which I'm quoting.
Github PRs can't be accepted, simply because of the fact that this repository is a mirror and any changes have to be pushed to the primary ffmpeg repository at https://git.videolan.org/.
And even then, classic patches via mail are preferred over that for review-reasons, and a link to a branch with the series applied can be optionally provided to more easily acquire them.
The contributing guide at ffmpeg.org should give you plenty of information on how to do all that.

**Comment by Sami32** [comment]
@BtbN Thanks for the explanation.
As a non english native, i find this totally confusing...

**Comment by retokromer** [comment]
I gave up to contribute. The mailing list is very rude.

**Comment by Sami32** [comment]
@retokromer I never tried such thing as mailing list, so this and the fact that's their contribution rules are not clear for me, make me think that my contribution will stop here. Very modest one though...

That's said, i love use FFmeg and will continue to report issues when met.

**Pull request closed without merging**
