### PR TITLE
qsv

### PR DESCRIPTION
**Pull request by Dreampursue**

### CODE REVIEW

**Comment by michaelni** [comment]
The README.md conflicts, the new information should probably be put into doc/
Also the docs should link to or contain documentation which works with ffmpeg.

**Comment by TimothyGu** [comment]
@Dreampursue I am closing this. This is @drocon11's WIP repository, and it should be @drocon11 who submits this PR.

**Comment by michaelni** [comment]
I agree that its best if the author submits his code, but if the author does not intend to do so or does not do so AND there is someone else who wants to do the work to integrate and test it then i prefer that over having to do the integration and testing myself. We now have some qsv code in FFmpeg git but it needs someone to test and if needed fix/improve/maintain it

**Comment by TimothyGu** [comment]
@michaelni on libav-devel Anton submitted a patch that is being reviewed and probably will be applied soon: https://lists.libav.org/pipermail/libav-devel/2015-March/068222.html

**Comment by Dreampursue** [comment]
I think I can do something for it. Now, I'm AE at Intel supporting for Media Server Studio. I can try to push it in Intel firstly. Or, I can do it individually. 

From my iPhone
Best regard!
Li Hui

On Mar 24, 2015, at 8:01 PM, Michael Niedermayer <notifications@github.com> wrote:

I agree that its best if the author submits his code, but if the author does not intend to do so or does not do so AND there is someone else who wants to do the work to integrate and test it then i prefer that over having to do the integration and testing myself. We now have some qsv code in FFmpeg git but it needs someone to test and if needed fix/improve/maintain it

**Comment by michaelni** [comment]
@TimothyGu yes, but that does not gurantee that the same patch will apply cleanly to FFmpeg nor that it will work in FFmpeg when applied and conflicts resolved, its much better if code has a dedicated maintainer in FFmpeg and is tested. If you want an example the avisynth commit today applied with 0 conflicts but did not work and required fixes.

**Comment by michaelni** [comment]
@Dreampursue, if there are things missing in FFmpeg, please submit patches to ffmpeg-devel. Also if there is overlap with antons patch then it would be best to keep the code similar to antons code, this should make it easier to move code back and forth between forks

**Pull request closed without merging**
