### PR TITLE
Convolutions with strides (convselective filter) for ffmpeg

### PR DESCRIPTION
**Pull request by kedartatwawadi**
I have modified the vf_convolution.c filter to be able to use strided convolution. As of now, I have created a new filter convselective.c which supports this feature. I had a few questions:
- Is strided convolutions a useful feature to have? 
- If so, would it be better to incorporate the same as options in the convolution filter, or have a new filter?
- I have used if, else statements to check if convolution needs to be performed at a location (separated by stride lengths). Is there a faster way of implementing this in c++, so that it does not slows things down?

(apologies if my questions/implementation seems naive)

Thanks

### CODE REVIEW

**Comment by richardpl** [comment]
What frame size is this one supposed to filter?

**Comment by kedartatwawadi** [comment]
Apologies for not explaining earlier:
1. The way in which it is implemented right now: it applies convolution filter (i.e performs convolution using the input filter) to specific grid points based on the x and y strides. It applies the identity filter at other points. 
2. It should support any generic frame size. 
3. It can be modified to obtain the standard "strided convolution"

**Comment by richardpl** [comment]
Usecase?

**Comment by kedartatwawadi** [comment]
Right now, I am using it for preprocessing on individual channels (adjusting gain, denoising), for demosaicing of video. 
https://en.wikipedia.org/wiki/Demosaicing

1. Also, on the same line, I think there is no demosaicing implementation in Ffmpeg (some discussion: https://ffmpeg.org/pipermail/ffmpeg-devel/2010-July/090493.html).
Would that be something useful?

**Comment by richardpl** [comment]
And what's up with quality? Filter just for demosaicing would be better idea.

**Comment by kedartatwawadi** [comment]
Sorry I did not understand your first question. Can you elaborate on the same?
Thanks for the response, I will submit a new pull for demosaicing once that is done.

**Comment by richardpl** [comment]
Quality of filtered output with this filtering approach.

**Comment by rdp** [comment]
Thanks for your contribution, please submit patch requests to the ffmpeg-devel mailing list instead of as github pull request, thanks!

**Pull request closed without merging**
