### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by kierank**

### CODE REVIEW

**Comment by TimothyGu** [comment]
I'm all for adding the code of conduct to the repo but why is this here rather than the mailing list? This repo is only a mirror (which I operate)

**Comment by kierank** [comment]
It's a github "one-click" button that adds a code of conduct to a repo, wanted to see what it actually does.

**Comment by kierank** [comment]
SAD!

**Comment by retokromer** [comment]
Due to recent budget cuts, the Code of Conduct has ben cut as well.

**Pull request closed without merging**
