### PR TITLE
unused variable 'ret'

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by TimothyGu** [comment]
Thanks for the patch! I will apply it soon, but note that for further contributions see #153.

**Comment by TimothyGu** [comment]
Closed by f8d685270e58.

**Comment by retokromer** [comment]
Thank you, @TimothyGu! I really would prefer not having to subscribe to ffmpeg-devel, because I am only an occasional contributor. Is there any other way to contribute?

**Comment by llogan** [comment]
You can send patches to ffmpeg-devel at ffmpeg.org (preverably via `git format-patch` or `git send-email`) without needing to subscribe. You'll have to wait up to a day for it to clear the moderation queue. Then you can check the [archives](https://lists.ffmpeg.org/pipermail/ffmpeg-devel/) for a reply, and/or in your message request that your address be added to CC in replies since you are unsubscribed. In the archives you can click the email address link of the replier if you want to reply to them: it will provide the necessary "in-reply-to" headers so your message will stay within the thread.

**Comment by retokromer** [comment]
Thank you, @llogan! I will delve into this part of git too, as I have some more code housekeeping to suggest.

**Pull request closed without merging**
