### PR TITLE
Update configure to better support OS/2

### PR DESCRIPTION
**Pull request by dmik**
This set of patches addresses several issues of `configure` when run on OS/2. The commit messages should be self-descriptive. This also needs to be back-ported to releases/2.8 (as this is what e.g. Firefox 38 needs).

### CODE REVIEW

**Comment by michaelni** [comment]
Please post this patchset to the ffmpeg-devel mailing list (and optionally CC KO Myung-Hun who maintains OS2 stuff in ffmpeg)
We dont really use github pull requests (i do occasionally review/apply some but this is not my area and i doubt any OS/2 people read this)

**Comment by dmik** [comment]
I really doubt there are any "OS/2 people" over there besides @komh, me, @dryeo, @psmedley and a few others who know each other and communicate anyway :) I will try ffmpeg-devel but the thing is that using mail lists is much less convenient than github pull requests. When you maintain several dozen of projects this may really become a problem. And for this reason the majority of OS/2 patches hang on our own branches in our own repositories (which of course sucks)...

**Comment by dryeo** [comment]
@dmik, I can post the patches to the mailing list as I'm already 
subscribed, if you'd like.

**Comment by dmik** [comment]
@dryeo Please do as I still haven't got my subscription confirmation et al.

**Pull request closed without merging**
