### PR TITLE
dash encoder. Correct generated manifest for MPEG-DASH MPD Validator …

### PR DESCRIPTION
**Pull request by Ligverd**
…and calculate current bandwidth for eath chunk. Now works correctly with dash.sj

### CODE REVIEW

**Comment by jumoog** [comment]
please submit patch requests to the ffmpeg-devel mailing list instead, thanks!

**Comment by Ligverd** [comment]
sorry for my stupidity, it is necessary to send on mail ffmpeg-devel@ffmpeg.org?

**Comment by jumoog** [comment]
https://www.ffmpeg.org/developer.html#Submitting-patches-1

**Comment by Ligverd** [comment]
moved to [https://trac.ffmpeg.org/ticket/5087](url)

**Pull request closed without merging**
